CREATE TABLE [dbo].[RSS]
(
	[RssId] INT NOT NULL PRIMARY KEY IDENTITY,
	[Title] NVARCHAR(50) NOT NULL ,
	[Auteur] NVARCHAR(50) NOT NULL ,
	[Inhoud] NVARCHAR(50) NOT NULL ,
	[Link] NVARCHAR(20) NOT NULL ,
	[PublicatieTijd] DATETIME NOT NULL 
	
)
